name: Draft
favicon: null
layout_spectrum: 0.2993460204452276
typography_spectrum: 0.8037526702973992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8510706827510148
  lightness: 0.6244719682727009
  saturation: 0.10346926446072757
  rhythmicContrast: 0.5998518434353173
purpose: []
