name: Draft
favicon: null
layout_spectrum: 0.99708
typography_spectrum: 0.13535
title: Draft Creative Co.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#706d6e'
    - '#c8c7c7'
    - '#999798'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
