name: Draft
favicon: null
layout_spectrum: 0.01097
typography_spectrum: 0.13535
title: workingdraft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#706d6e'
    - '#c8c7c7'
    - '#999798'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
