name: Draft
favicon: null
layout_spectrum: 0.49393
typography_spectrum: 1
title: workingdraft
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#706d6e'
    - '#c8c7c7'
    - '#999798'
  brandStrength: 0.8510706827510148
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
